<?php

/**
 * Implements hook_node_insert().
 */
function teach_it_media_node_insert($node)
{
    if($node->type = 'article'){
        global $base_url;
        $title = $node->title;
        module_load_include('inc', 'pathauto', 'pathauto'); // include the inc file for Pathauto module

        pathauto_create_alias('node', 'insert', 'node/'.$node->nid, array('node' => $node), $node->type); // Language is optional
        $alias = drupal_get_path_alias('node/'.$node->nid);
        $alias = $base_url.'/'.$alias;
        $url = '';
        if(isset($node->field_media_multi['und'][0]['fid'])){
            $file = file_load($node->field_media['und'][0]['fid']);
            $e_mine = explode('/',$file->filemime);
            $mine = $e_mine[0];
            switch ($mine){
                case 'video':
                    $vid = explode('/',$file->uri);
                    if($e_mine[1] =='youtube'){
                        $url = 'https://img.youtube.com/vi/'.$vid[3].'/hqdefault.jpg';
                    }elseif ($e_mine[1]=='vimeo'){
                        $hash = unserialize(file_get_contents("http://vimeo.com/api/v2/video/".$vid[3].".php"));
                        $url = $hash[0]["thumbnail_large"];
                    }else{

                    }
                    break;
                case 'image':
                    $url = file_create_url($file->uri);
                    break;
            }
        }
      if(strpos( $_SERVER['HTTP_HOST'], 'education') !== false || strpos( $_SERVER['HTTP_HOST'], 'teachitinc') !== false){
        _teach_it_media_tweet($title.' '.$alias,$url);
      }
    }
}
function _teach_it_media_tweet($message,$image) {

// add the codebird library
    require_once('codebird/src/codebird.php');

  if(strpos( $_SERVER['HTTP_HOST'], 'education') !== false){
    $consumerKey = 'OnO4S0vrojZudtOologD76uJX';
    $consumerSecret = '8UI3scEcq2jh5wfEy6BIQimD6kY7oRkVJPkeyvmGVTRnyNYmSo';
    $accessToken = '952565968949035008-2nAoLoDd6MQJ0IzMm6jYJjfzffcvJcD';
    $accessTokenSecret = 'LUDzrJAWxHar77ejUjvbVaShOLUDsd8lqp9oL29TsZYJ4';
  }else{
    $consumerKey = 'ZggIFfl81XKHC1bWmiqHWpHUV';
    $consumerSecret = 'LunLAs4aqKbG6HEADVkXGd75vBttq2XIOAQQTYwAzparOjZbCr';
    $accessToken = '225914566-xuy2QIarPGGJdWMmTJUICkPkR0ZT89s1VAzvILQK';
    $accessTokenSecret = 'e50LyJzqOVNRal5x8qq1mwGEVMAEbfP5MnuAW4bTQb4aS';
  }
// note: consumerKey, consumerSecret, accessToken, and accessTokenSecret all come from your twitter app at https://apps.twitter.com/
    \Codebird\Codebird::setConsumerKey($consumerKey, $consumerSecret);
    $cb = \Codebird\Codebird::getInstance();
    $cb->setToken($accessToken, $accessTokenSecret);

//build an array of images to send to twitter
    if($image){
        $reply = $cb->media_upload(array(
            'media' => $image
        ));
//upload the file to your twitter account
        $mediaID = $reply->media_id_string;
    }else{
        $mediaID = '';
    }

//build the data needed to send to twitter, including the tweet and the image id
    $params = array(
        'status' => $message,
        'media_ids' => $mediaID
    );
//post the tweet with codebird

    $cb->statuses_update($params);

}

/**
 * Implements hook_form_alter().
 */
function teach_it_media_form_alter(&$form, &$form_state, $form_id)
{
  switch ($form_id){
    case 'contact_site_form':
      break;
  }
}
